
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for s3 bucket configuration

Parameters:
  S3BucketName:
    Description: Enter S3 Bucket Name 
    Type: String

  VersioningConfiguration: 
    Type: String
    Description: Status Of Versioning
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled

  #blockpublicACls:
    #Type: String
    #Description: Block Public ACLs
    #AllowedValues:
     # - true
      #- false
    #Default: true

Resources:
  S3Bucket:
    #DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            #Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: Dev
      
Outputs:
  BucketName: 
    Value: !Ref S3BucketName


      




        








