
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for s3 bucket configuration

Parameters:
  S3BucketName:
    Description: Enter S3 Bucket Name 
    Type: String

  VersioningConfiguration: 
    Type: String
    Description: Status Of Versioning
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled

  #objectlockconfiguration:
   # Type: String
    #Description: 
    #AllowedValues:
     # - Enabled
      #- Disabled
    #Default: Enabled

  
  blockpublicAcls:
    Type: String
    Description: Block Public ACLS
    AllowedValues:
      - true
      - false
    Default: true

  blockpublicpolicy:
    Type: String
    Description: Block Public Policy
    AllowedValues:
      - true
      - false
    Default: true

  ignorepubliccAcls:
    Type: String
    Description: Block Public ACLS
    AllowedValues:
      - true
      - false
    Default: true

  restrictpublicbuckets:
    Type: String
    Description: Block Public ACLS
    AllowedValues:
      - true
      - false
    Default: true 

Resources:
  S3Bucket:
    #DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration
      
     # ObjectLockEnabled: true
      #ObjectLockConfiguration:
        #ObjectLockEnabled: Enabled
       # Rule:
        ##   Mode: Goverance
          #  Days: 1
        
    # AccessControl: Private  

    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: error.html

    LifecycleConfiguration:
      Rules:
        - Id: GlacierRule
            #Prefix: glacier
          Status: Enabled
          ExpirationInDays: 365
          Transitions:
            - TransitionInDays: 1
              StorageClass: GLACIER
                
    PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref blockpublicAcls
        BlockPublicPolicy: !Ref blockpublicpolicy
        IgnorePublicAcls: !Ref ignorepubliccAcls
        RestrictPublicBuckets: !Ref restrictpublicbuckets 

    OwnerShipControls:
      Rules:
        - ObjectOwnership: BucketOwnerenforced 

                 
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            #KMSMasterKeyID: Kms-Key-ARN
            SSEAlgorithm: 'aws:kms'
      
    Tags:
      - Key: Name
        Value: Dev
      
Outputs:
  BucketName: 
    Value: !Ref S3BucketName

  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3

  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Name of AWS S3 bucket to hold website content


  



      




        








