



AWSTemplateFormatVersion: 2010-09-09


Parameters:
  S3BucketName:
    Description: Enter S3 Bucket Name 
    Type: String

  versioningconfiguration: 
    Type: String
    Description: Status Of Versioning
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled

  accesscontrol:
    Type: String
    Description: Select Accesscontrol 
    AllowedValues:
      - BucketOwnerFullControl
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthnticatedRead
      - LogDeliverywRITE
      - BucketOwnerRead
      - AwsExecRead
    Default: BucketOwnerFullControl


Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

      VersioningConfiguration:
        Status: !Ref versioningconfiguration

      AccessControl: !Ref accesscontrol

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced