

AWSTemplateFormatVersion: '2010-09-09'
Description: create s3 bucket ownership

Parameters:
  S3BucketName:
    Description: Enter S3 Bucket Name 
    Type: String

  versioningconfiguration: 
    Type: String
    Description: Status Of Versioning
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled

  objectlockenabled:
    Type: String
    AllowedValues: 
      - true
      - false
    Default: true

  #ownershipcontrols:
   # Type: String
    #Description: create ownership of objects
    #AllowedValues:
    #  - BucketOwnerEnforced
     # - BucketOwnerPreferred
     # - ObjectWriter
   # Default: BucketOwnerEnforced 

  accesscontrol:
    Type: String
    Description: Select Accesscontrol 
    AllowedValues:
      - BucketOwnerFullControl
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthnticatedRead
      - LogDeliverywRITE
      - BucketOwnerRead
      - AwsExecRead
    Default: BucketOwnerFullControl

  blockpublicAcls:
    Type: String
    Description: Block Public ACLS
    AllowedValues:
      - true
      - false
    Default: true

  blockpublicpolicy:
    Type: String
    Description: Block Public Policy
    AllowedValues:
      - true
      - false
    Default: true

  ignorepubliccAcls:
    Type: String
    Description: Block Public ACLS
    AllowedValues:
      - true
      - false
    Default: true

  restrictpublicbuckets:
    Type: String
    Description: Block Public ACLS
    AllowedValues:
      - true
      - false
    Default: true 

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

      VersioningConfiguration:
        Status: !Ref versioningconfiguration

      AccessControl: !Ref accesscontrol

      #OwnerShipControls: !Ref ownershipcontrols

      ObjectLockEnabled: !Ref objectlockenabled
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule: 
          DefaultRetention:
            Mode: Goverence
            Days: "1"

      OwnerShipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced   

      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            #Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
                
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref blockpublicAcls
        BlockPublicPolicy: !Ref blockpublicpolicy
        IgnorePublicAcls: !Ref ignorepubliccAcls
        RestrictPublicBuckets: !Ref restrictpublicbuckets

      
        