

AWSTemplateFormatVersion: '2010-09-09'
Description: create s3 bucket ownership

Parameters:
  objectownership:
    Type: String
    Description: create ownership of objects
    AllowedValues:
      - BucketOwnerEnforced
      - BucketOwnerPreferred
      - ObjectWriter
    Default: BucketOwnerEnforced

  accesscontrol:
    Type: String
    Description: Select Accesscontrol 
    AllowedValues:
      - BucketOwnerFullControl
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthnticatedRead
      - LogDeliverywRITE
      - BucketOwnerRead
      - AwsExecRead
    Default: BucketOwnerFullControl




Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: !Ref accesscontrol

      ObjectOwnerShip: !Ref objectownership

      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule: 
          DefaultRetention:
            Mode: Goverence
            Days: "1"

      
        