AWSTemplateFormatVersion: 2010-09-09

Properties:
  ObjectOwnership:
  Type: String
  Description: create ownership of objects
  AllowedValues:
    - BucketOwnerEnforced
    - BucketOwnerPreferred
    - ObjectWriter



Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      OwnershipControls: !Ref ObjectOwnership
        