
AWSTemplateFormatVersion: '2010-09-09'
Description: test s3 object configuaration

Parameters:
  S3BucketName:
    Description: Enter S3 Bucket Name 
    Type: String

  versioningconfiguration: 
    Type: String
    Description: Status Of Versioning
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled


  objectlockenabled:
    Type: String
    AllowedValues: 
      - true
      - false
    Default: true

  accesscontrol:
    Type: String
    Description: Select Accesscontrol 
    AllowedValues:
      - BucketOwnerFullControl
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthnticatedRead
      - LogDeliverywRITE
      - BucketOwnerRead
      - AwsExecRead
    Default: BucketOwnerFullControl

  Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

      VersioningConfiguration:
        Status: !Ref versioningconfiguration

      AccessControl: !Ref accesscontrol

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

      ObjectLockEnabled: !Ref objectlockenabled
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule: 
          DefaultRetention:
            Mode: Goverence
            Days: "1"

  
